INSERT INTO CITY (NAME) VALUES ('Budapest');
INSERT INTO CITY (NAME) VALUES ('Debrecen');

INSERT INTO STATUS (DESCRIPTION) VALUES ('submitted');
INSERT INTO STATUS (DESCRIPTION) VALUES ('processing');
INSERT INTO STATUS (DESCRIPTION) VALUES ('under delivery');
INSERT INTO STATUS (DESCRIPTION) VALUES ('delivered');

INSERT INTO CATEGORY (ID, NAME) VALUES (0, 'Deleted product category');
INSERT INTO CATEGORY (NAME) VALUES ('Pizza');
INSERT INTO CATEGORY (NAME) VALUES ('Spaghetti');

INSERT INTO RESTAURANT (ZIP_CODE, CITY_ID, ADDRESS, OPEN_HOUR_WEEKDAY, CLOSE_HOUR_WEEKDAY, OPEN_HOUR_WEEKEND, CLOSE_HOUR_WEEKEND, PHONE_NUMBER) VALUES (1000, 1, 'Restaurant way 1', 10, 18, 10, 22, '+36201234567');
INSERT INTO RESTAURANT (ZIP_CODE, CITY_ID, ADDRESS, OPEN_HOUR_WEEKDAY, CLOSE_HOUR_WEEKDAY, OPEN_HOUR_WEEKEND, CLOSE_HOUR_WEEKEND, PHONE_NUMBER) VALUES (1000, 1, 'Restaurant way 2', 8, 20, 8, 20, '+36205555555');
INSERT INTO RESTAURANT (ZIP_CODE, CITY_ID, ADDRESS, OPEN_HOUR_WEEKDAY, CLOSE_HOUR_WEEKDAY, OPEN_HOUR_WEEKEND, CLOSE_HOUR_WEEKEND, PHONE_NUMBER) VALUES (4000, 2, 'Restaurant way 10', 10, 20, 10, 22, '+36207777777');

INSERT INTO USER (EMAIL, FIRST_NAME, LAST_NAME, PASSWORD_HASH, ZIP_CODE, CITY_ID, ADDRESS, PHONE_NUMBER, RESTAURANT_ID, IS_ADMIN) VALUES ('admin@restaurant.com', 'Restaurant', 'Admin', '$2a$10$ZS3QP8/EscaGk1RseWpHXu5zjNMEq2RzeJdbjn1vgW0vfaXOX09Nu', 1000, 1, 'Main street 1', '+36301234567', 1, TRUE); --password: 'admin'
INSERT INTO USER (EMAIL, FIRST_NAME, LAST_NAME, PASSWORD_HASH, ZIP_CODE, CITY_ID, ADDRESS, PHONE_NUMBER, RESTAURANT_ID) VALUES ('user1@gmail.com', 'User', 'One', '$2a$10$GzsmSn8PwIHpq.eEOQ4lYO4cBlApL.vBWSFf7dx2/g0781i/3HB12', 1000, 1, 'XXX street 1', '+36308888888', 1); --password: 'one'
INSERT INTO USER (EMAIL, FIRST_NAME, LAST_NAME, PASSWORD_HASH, ZIP_CODE, CITY_ID, ADDRESS, PHONE_NUMBER, RESTAURANT_ID) VALUES ('user2@gmail.com', 'User', 'Two', '$2a$10$KmZWgak/IqfJAdIIOOeue.BYo/nzCZta0dwSgjj9gjdnz.qUqEqc2', 4000, 2, 'YYY street 1', '+36309999999', 3); --password: 'two'

INSERT INTO PRODUCT (ID, NAME, CATEGORY_ID, DESCRIPTION, PRICE) VALUES (0, 'Deleted product', 0, 'Deleted product', 0);
INSERT INTO PRODUCT (NAME, CATEGORY_ID, DESCRIPTION, PRICE) VALUES ('Margherita', 1, 'tomato sauce, cheese', 10);
INSERT INTO PRODUCT (NAME, CATEGORY_ID, DESCRIPTION, PRICE) VALUES ('Hawaii', 1, 'tomato sauce, ham, pineapple, cheese', 13);
INSERT INTO PRODUCT (NAME, CATEGORY_ID, DESCRIPTION, PRICE) VALUES ('Bolognese', 2, '', 8);

INSERT INTO "order" (USER_ID, CREATE_DATE, NOTE, STATUS_ID) VALUES (2, PARSEDATETIME('28-10-17 20:00:00', 'dd-MM-yy hh:mm:ss'), 'Please hurry!', 4);
INSERT INTO "order" (USER_ID, CREATE_DATE, NOTE, STATUS_ID) VALUES (2, PARSEDATETIME('29-10-17 22:00:00', 'dd-MM-yy hh:mm:ss'), '', 1);

INSERT INTO ORDER_PRODUCT ("order_id", PRODUCT_ID, QUANTITY) VALUES (1, 2, 2);
INSERT INTO ORDER_PRODUCT ("order_id", PRODUCT_ID, QUANTITY) VALUES (1, 3, 1);
INSERT INTO ORDER_PRODUCT ("order_id", PRODUCT_ID, QUANTITY) VALUES (2, 2, 1);

INSERT INTO REVIEW (CREATE_DATE, PRODUCT_ID, USER_ID, STARS, DESCRIPTION) VALUES (PARSEDATETIME('28-10-17 23:00:00', 'dd-MM-yy hh:mm:ss'), 3, 2, 5, 'Very delicious!');
